stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - data/creditcard.csv
      - src/preprocessing.py
    params:
      - preprocessing.test_size
      - preprocessing.val_size
      - preprocessing.random_state
    outs:
      - data/scaler.pkl
      - data/processed_train.csv
      - data/processed_val.csv
      - data/processed_test.csv
